### ISSUE TITLE
404 for "anatomy of a plugin"

### ISSUE THREAD

**Issue by garethrbrown** [marcusolsson/obsidian-plugin-docs#2]
There is a 404 for this link https://marcus.se.net/obsidian-plugin-docs/getting-started/plugin-anatomy, which is linked at the bottom of https://marcus.se.net/obsidian-plugin-docs/getting-started/create-your-first-plugin ("Once you're ready, learn more about the anatomy of a plugin.")

**Comment by marcusolsson** [comment]
Thanks for the heads-up! Should be fixed now!

**Comment by garethrbrown** [comment]
Thanks for the fix :)
