### ISSUE TITLE
"Mardown post processing" page error

### ISSUE THREAD

**Issue by kuechlerm** [marcusolsson/obsidian-plugin-docs#62]
https://marcus.se.net/obsidian-plugin-docs/editor/markdown-post-processing says 
"If you want to change how a Markdown document is rendered in ##Preview mode##, you can add your own Markdown post processor." but I think it should say "Reading" / "Read mode".

Thanks for the project, very helpful.

**Comment by marcusolsson** [comment]
Thank you for the heads-up! 🙏
